name: Swagger

on:
  push:
    branches:
      -  master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - run: 
        go install github.com/swaggo/swag/cmd/swag
    - name: Generate Swagger documentation
      run: swag init -g ./run/main.go -o ./swagger/docs

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: test/swagger:${{ github.sha }}
        file: swagger/Dockerfile